ResidenciaTICBrisa/T2G7-Revista-Darcy

- docs/visao_de_produto.md
Descrever a Posição do Produto com o problema identificado e propostas para a nova plataforma. Relatar tecnologias a serem utilizadas e objetivos.
Etapas necessárias para resolução do problema:
Plataforma atual: https://revistadarcy.unb.br/
> Adicionando Visão do Produto

- docs/visao_de_projeto.md
- mkdocs.yml
Criação da visão de projeto.
Criação da visão de projeto e inserção de todos os tópicos.
> Adição da visão de projeto

- docs/index.md
- docs/politicas/conduta.md
- docs/sprints/sprint00/planejamento.md
- docs/sprints/sprint00/resultados.md
- mkdocs.yml
Reorganizei a navegação do MKDOCS e criei a documentação da sprint 00.
Reorganização da navegação do MKDOCS e adição de documentação da sprint 00.
Adicione qualquer outra informação relevante que possa ajudar a entender ou revisar este pull request.
> Documentação da Sprint 00 e Reorganização da Navegação do MKDOCS

- docs/atas/ata01.md
- docs/atas/ata02.md
- docs/politicas/branches.md
- docs/politicas/commit.md
- docs/politicas/conduta.md
- docs/politicas/plano-de-comunicacao.md
- docs/requisitos/visao_de_produto.md
- docs/requisitos/visao_de_projeto.md
- docs/sprints/sprint00/resultados.md
- docs/sprints/sprint01/planejamento.md
- docs/sprints/sprint01/resultados.md
- mkdocs.yml
Adicionei atas 00 e 01 e padronizei o MKDOCS.
Atas e padronização.
> (#19): adicao de atas e padronizacao do mkdocs

- docs/atas/ata01.md
- docs/politicas/branches.md
- docs/sprints/sprint01/resultados.md
- docs/sprints/sprint02/planejamento.md
- docs/sprints/sprint02/resultados.md
Atualização da documentação. Planejamento e Resultados da Sprint 02.
Nada a declarar.
> planejamento e resultados da sprint 02

- docs/requisitos/visao_de_projeto.md
Nesta atividade foi realizado o Roadmap do projeto definindo as datas das Sprint's e cada Release. Também foi definido a proposta de entrega em cada etapa do projeto.
[Adicione qualquer outra informação relevante que possa ajudar a entender ou revisar este pull request.](https://www.canva.com/design/DAGAnS3sCIY/VoGZAanzWNjTIhAU2HFVVg/edit?utm_content=DAGAnS3sCIY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
> Adicionando Roadmap do Projeto

- docs/requisitos/backlog.md
- docs/requisitos/visao_de_projeto.md
- mkdocs.yml
Foi adicionado os requisitos elicitados e refinados. 
Foi utilizado o User Story Map para mapear as US's e a partir do MoSCoW identificado as US's implementadas durante a Release 1. 
Liste as principais mudanças propostas neste pull request.
> Adicionando Requisitos Elicitados e US's implementadas para a Release 1

- docs/atas/equipe_cliente/ata03.md
- mkdocs.yml
ata da reunião 03 com a SECOM
ata da reunião 03 com a SECOM
Adicione qualquer outra informação relevante que possa ajudar a entender ou revisar este pull request.
>  ata da reunião 03 com a SECOM

- docs/atas/equipe_cliente/ata03.md
Adicionando o link da reunião 3 com a cliente.
Adicionar o link da reunião
> Link da reunião 3

- docs/atas/equipe_cliente/ata03.md
- docs/atas/equipe_cliente/ata04.md
- mkdocs.yml
Adição da ata da quarta reunião com a cliente.
> Ata da reuniao 04 com a SECOM

- docs/requisitos/backlog.md
- docs/requisitos/visao_de_produto.md
Foi criado o diagrama de Causa e Efeito e Requisitos Não Funcionais da Release 1.
Liste as principais mudanças propostas neste pull request.
> Adicionando diagrama de Causa e Efeito e Requisitos Não Funcionais

- docs/atas/equipe/ata04.md
- docs/release/release1.md
- docs/requisitos/visao_de_projeto.md
- docs/sprints/sprint04/planejamento.md
- mkdocs.yml
Adicionado todo o planejamento da sprint 04, além de uma correção no documento da release 1.
> planning da sprint 04

- docs/requisitos/perfil_dos_usuarios.md
Correção da exibição dos dados de perfil.
> :bug: raw fix

- docs/requisitos/perfil_dos_usuarios.md
Definindo Perfil dos Usuários
Liste as principais mudanças propostas neste pull request.
Adicione qualquer outra informação relevante que possa ajudar a entender ou revisar este pull request.
> Definindo Perfil dos Usuários

- docs/atas/equipe_cliente/ata05.md
- mkdocs.yml
Ata da quinta reunião com a cliente.
> :fire: ata da quinta reunião

- docs/atas/equipe/ata05.md
- docs/atas/equipe_cliente/ata05.md
- docs/atas/equipe_cliente/ata06.md
- docs/sprints/sprint04/resultados.md
- docs/sprints/sprint05/planejamento.md
- mkdocs.yml
Adicionado o planejamento da quinta sprint, além da ata da sexta reunião com a SECOM e a ata da quinta reunião interna.
> :fire: Planning da sprint 05 e ata da reuniao 06 com a SECOM | Ata da Reunião 05 interna

- docs/atas/equipe_cliente/ata07.md
- mkdocs.yml
Adicionado a ata da sétima reunião com a SECOM.
Adicione qualquer outra informação relevante que possa ajudar a entender ou revisar este pull request.
> :books: docs - ata da reuniao 07 com a SECOM

- docs/atas/equipe/ata06.md
- docs/sprints/sprint03/planejamento.md
- docs/sprints/sprint04/planejamento.md
- docs/sprints/sprint05/planejamento.md
- docs/sprints/sprint05/resultados.md
- docs/sprints/sprint06/planejamento.md
- mkdocs.yml
Adição da aba "resultados" da sprint 05 e do planejamento da sprint 06. Além da ata da reunião interna 06.
> :books: docs - sprint 05 review e sprint 06 plann

- docs/atas/equipe_cliente/ata08.md
- mkdocs.yml
Ata da oitava reunião com a SECOM.
> :books: docs - ata da reuniao 08 com a SECOM

- README.md
- docs/atas/equipe/ata07.md
- docs/atas/equipe_cliente/ata08.md
- docs/atas/equipe_cliente/ata09.md
- docs/index.md
- docs/sprints/sprint06/resultados.md
- docs/sprints/sprint07/planejamento.md
- docs/sprints/sprint07/resultados.md
- mkdocs.yml
Adicionado a ata da reunião 09 com a SECOM, além dos resultados da sprint 06 e o planejamento da sprint 07. 
closes #88 
> :books: docs - sprint 06 fechada e srint 07 plann

- docs/atas/equipe/ata08.md
- docs/atas/equipe_cliente/ata10.md
- docs/sprints/sprint07/planejamento.md
- docs/sprints/sprint07/resultados.md
- docs/sprints/sprint08/planejamento.md
- docs/sprints/sprint08/resultados.md
- mkdocs.yml
Adicionado a ata da reunião 10 com a SECOM, além dos resultados da sprint 07 e o planejamento da sprint 08. 
closes #95 
> :books: docs - sprint 07 fechada e sprint 08 plann

- docs/atas/equipe/ata09.md
- docs/sprints/sprint08/planejamento.md
- docs/sprints/sprint08/resultados.md
- docs/sprints/sprint09/planejamento.md
- docs/sprints/sprint09/resultados.md
- mkdocs.yml
Adicionado os resultados da sprint 08 e o planejamento da sprint 09.
> :books: docs - sprint 08 fechada e sprint 09 plann

- docs/atas/equipe_cliente/ata12.md
- docs/sprints/sprint09/planejamento.md
- mkdocs.yml
Ata da reunião 12 com a SECOM.
Adição das issues criadas até o momento da sprint 09.
> :books: docs - ata da reuniao 12 com a secom

- docs/atas/equipe_cliente/ata13.md
- docs/sprints/sprint09/planejamento.md
- docs/sprints/sprint09/resultados.md
- mkdocs.yml
Resultados da Sprint 09 adicionados ao MKDOCS.
> :books: docs - sprint 09 results

- docs/workshop/comandos.md
- mkdocs.yml
> :books: docs - workshop

- docs/atas/equipe/ata10.md
- docs/atas/equipe_cliente/ata14.md
- docs/atas/equipe_cliente/ata15.md
- docs/sprints/sprint09/planejamento.md
- docs/sprints/sprint10/planejamento.md
- docs/sprints/sprint10/resultados.md
- mkdocs.yml
closes #126 
Foam adicionadas as atas da reunião interna 10, e das reuniões externas 14 e 15. Além disso, foram adicionados o planejamento e os resultados da sprint 10.
> :books: docs - atas, planejamentos e results

- docs/atas/equipe/ata11.md
- docs/sprints/sprint11/planejamento.md
- docs/sprints/sprint11/resultados.md
- mkdocs.yml
Adicionado o Planejamento e Resultados da Sprint 11 no mkdocs
> Planejamento e Resultados da Sprint 11

- docs/atas/equipe_cliente/ata16.md
- mkdocs.yml
Ata da reunião 16 com a SECOM.
> :books: docs - ata da reuniao 16 com a secom
